apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
  namespace: myapp
  labels:
    app: web-app
spec:
  replicas: 10
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-container
        image: nginx:1.25
        ports:
        - containerPort: 80

