apiVersion: v1
kind: Service
metadata:
  name: my-backend-service
  namespace: myapp
  labels:
    app: backend
spec:
  type: ClusterIP
  selector:
    app: my-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

